In [144]:
import tensorflow as tf
from IPython.display import clear_output
import numpy as np

In [145]:
mnist = tf.keras.datasets.mnist

In [146]:
dataset = mnist.load_data()

In [147]:
import matplotlib.pyplot as plt

In [148]:
def img_to_array(x):
    ##plt.imshow(x,cmap="gray")
    res=[]
    for j in x:
        for k in j:
            if (k<=128):
                res.append(0)
            else:
                res.append(1)
    return res

In [149]:
def array_show(x):
    c=np.array(x)
    x=c.reshape(28,28)
    
    plt.imshow(x,cmap="gray")

In [150]:
theta1=np.random.uniform(-0.1,0.1,(784,784))
print(theta1)
theta2=np.random.uniform(-0.1,0.1,(10,784))

[[ 0.04301462 -0.0474118   0.08066346 ... -0.03472342 -0.0101463
  -0.0429578 ]
 [-0.04684893 -0.05482087  0.010943   ...  0.05175148  0.03092444
   0.09844524]
 [ 0.05294365 -0.04613643  0.09501068 ...  0.09391947 -0.06748213
  -0.00432299]
 ...
 [-0.09175521  0.06067074  0.00151491 ...  0.05111187 -0.09887461
  -0.03755586]
 [ 0.06287907 -0.05705372 -0.03288023 ...  0.01730758  0.01172843
  -0.01270205]
 [-0.0123097   0.03680634 -0.06004335 ... -0.0676607   0.0302253
   0.02689929]]


In [151]:
def sigmoid(x):
    res=[]
    for i in x:
        for j in i:
            res.append(1/(1+np.exp(-j)))
    return res

In [152]:
def create_vector(x):
    c=np.array([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]).reshape(10,1)
    c[x]=c[x]+1.0


    return c

In [ ]:
count=0
for i in x1:
    clear_output(wait=True)
    xi=np.array(img_to_array(i)).reshape(784,1)
    v=np.matmul(theta1,xi)
    xh=np.array(sigmoid(np.matmul(theta1,xi))).reshape(784,1)
    xo=np.array(sigmoid(np.matmul(theta2,xh))).reshape(10,1)
    yo=create_vector(y1[count])
    ##backpropagation beaware of indices
    error1=np.subtract(xo,yo)
    error2=np.matmul(theta2.transpose(),error1)
    delta1=np.matmul(np.dot(np.multiply(np.multiply(xo,(1-xo)),error1),0.1),xh.transpose())
    theta2=np.subtract(theta2,delta1)
    delta2=np.matmul(np.dot(np.multiply(np.multiply(xh,(1-xh)),error2),0.1),xi.transpose())
    theta1=np.subtract(theta1,delta2)
    count=count+1
    print(xo)
    print(error1)
    print(yo)
    print(count)

[[4.66337873e-06]
 [9.62342574e-01]
 [1.85417527e-02]
 [3.44746532e-02]
 [1.27123695e-02]
 [3.65704716e-02]
 [5.56337667e-02]
 [1.13133311e-02]
 [8.91151859e-04]
 [6.48152411e-03]]
[[ 4.66337873e-06]
 [-3.76574256e-02]
 [ 1.85417527e-02]
 [ 3.44746532e-02]
 [ 1.27123695e-02]
 [ 3.65704716e-02]
 [ 5.56337667e-02]
 [ 1.13133311e-02]
 [ 8.91151859e-04]
 [ 6.48152411e-03]]
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
1711


In [141]:
count=1
account=0
sq=0
sum=0.0
for i in range(0,10000):
    clear_output(wait=True)
    xi=np.array(img_to_array(x2[i])).reshape(784,1)
    xh=np.array(sigmoid(np.matmul(theta1,xi))).reshape(784,1)
    xo=np.array(sigmoid(np.matmul(theta2,xh))).reshape(10,1)
    yo=create_vector(y2[i])
    result1 = np.where(xo == np.amax(xo))
    result2 = np.where(yo == np.amax(yo))
    if (result1==result2):
        account=account+1
    accuracy=account/count
    count=count+1
    print(accuracy)
    print(count)

0.9127
10001
